### PR TITLE
Jsdom v11.12.0 adds localStorage and sessionStorage

### PR DESCRIPTION
**Pull request by geoffdutton**
In version 11.12.0, [jsdom added localStorage and sessionStorage](https://github.com/jsdom/jsdom/commit/4d26c6773f011205d9c703cc5988e7c117efea31#diff-9b8fab691c00b9e5380b19ce882f3271R1), so simply overwriting `global.localStorage` and `global.sessionStorage` doesn't work.

More on the issue here: https://github.com/jsdom/jsdom/issues/2304

This is my hacky fix, not sure if there is a better way.

This is also only an issue when using `--env=jsdom` for jest.

### CODE REVIEW

**Comment by Kocal** [comment]
Any updates on this? :thinking:

**Comment by adieCodes** [comment]
Would be great to get this merged, I can't seem to get any of the workarounds to work. Thanks in advance for all your work 👍

**Comment by AlexandrLi** [comment]
Guys, any updates on this?

**Comment by geoffdutton** [comment]
I fixed the conflicts with yarn.lock.

**Comment by th3fallen** [comment]
@clarkbw could you tag this so we could consume it via yarn please sir?

**Comment by clarkbw** [comment]
@th3fallen Release coming in https://github.com/clarkbw/jest-localstorage-mock/pull/92

There were build errors that didn't allow me to publish

**Comment by Kocal** [comment]
Thanks you @clarkbw! :tada:

**Pull request merged**
